import Card from "@/components/common/Card";
import {
    FileText,
    AlertTriangle,
    Wrench,
    ShieldCheck,
    BookOpen,
    Bot,
} from "lucide-react";

const Section = ({ icon: Icon, title, children }) => (
    <div className="rounded-xl border border-border bg-background p-5">

        <div className="mb-3 flex items-center gap-2">

            <Icon size={18} className="text-primary" />

            <h3 className="font-semibold text-foreground">

                {title}

            </h3>

        </div>

        {children}

    </div>
);

const List = ({ items }) => {

    if (!items?.length) {

        return (

            <p className="text-muted">

                Not available.

            </p>

        );

    }

    return (

        <ul className="space-y-2">

            {

                items.map((item, index) => (

                    <li
                        key={index}
                        className="flex gap-3"
                    >

                        <span className="mt-2 h-2 w-2 rounded-full bg-primary" />

                        <span>{item}</span>

                    </li>

                ))

            }

        </ul>

    );

};

const PostmortemCard = ({ postmortem }) => {

    if (!postmortem) {

        return (

            <Card
                title="AI Postmortem"
                subtitle="Generated after incident resolution."
            >

                <div className="flex h-56 items-center justify-center rounded-xl border border-dashed border-border">

                    <p className="text-muted">

                        No postmortem generated yet.

                    </p>

                </div>

            </Card>

        );

    }

    return (

        <Card
            title="AI Postmortem"
            subtitle={`Generated by ${postmortem.generatedBy}`}
        >

            <div className="space-y-5">

                <Section
                    icon={FileText}
                    title="Summary"
                >

                    <p className="leading-7 text-muted">

                        {postmortem.summary}

                    </p>

                </Section>

                <Section
                    icon={AlertTriangle}
                    title="Impact"
                >

                    <p className="leading-7 text-muted">

                        {postmortem.impact}

                    </p>

                </Section>

                <Section
                    icon={Bot}
                    title="Root Cause"
                >

                    <p className="leading-7 text-muted">

                        {postmortem.rootCause}

                    </p>

                </Section>

                <Section
                    icon={Wrench}
                    title="Resolution"
                >

                    <p className="leading-7 text-muted">

                        {postmortem.resolution}

                    </p>

                </Section>

                <Section
                    icon={ShieldCheck}
                    title="Preventive Actions"
                >

                    <List
                        items={postmortem.preventiveActions}
                    />

                </Section>

                <Section
                    icon={BookOpen}
                    title="Lessons Learned"
                >

                    <List
                        items={postmortem.lessonsLearned}
                    />

                </Section>

            </div>

        </Card>

    );

};

export default PostmortemCard;